Improve the error messages

diff --git a/builder/build-image b/builder/build-image
--- a/builder/build-image
+++ b/builder/build-image
@@ -2,13 +2,15 @@
 set -euo pipefail
 
 die() {
-	echo "$@" >&2
+	echo "Error: $*" >&2
 	exit 1
 }
 
 # build the boot files
 build() {
 	local cmdline initrd
+
+	[[ -d "$root_dir" ]] || die "the root directory '$root_dir' does not exist"
 
 	pushd "$root_dir" >/dev/null
 
@@ -51,7 +53,7 @@ compress() {
 		zstd -19 -T0
 		;;
 	*)
-		die "Invalid compression scheme: $compression"
+		die "invalid compression scheme '$compression'"
 		;;
 	esac
 }
@@ -140,7 +142,7 @@ set_format() {
 		format="$1"
 		;;
 	*)
-		die "Invalid format: $1"
+		die "invalid format '$1'"
 		;;
 	esac
 }
@@ -199,10 +201,10 @@ while [[ "$#" -gt 0 ]]; do
 			shift 2
 			;;
 		-*)
-			die "Invalid option: $1"
+			die "invalid option '$1'"
 			;;
 		*)
-			die "Invalid parameter: $1"
+			die "invalid parameter '$1'"
 			;;
 	esac
 done
